tunnel: 98614298-580f-4c01-a400-876bab87a633
credentials-file: C:\Users\Owner\.cloudflared\98614298-580f-4c01-a400-876bab87a633.json

ingress:
  # EMTeeGee subdomain - direct to Django app
  - hostname: emteegee.tcgplex.com
    service: http://localhost:8001
  
  # Catch all
  - service: http://localhost:8001

# Additional settings
no-autoupdate: true
protocol: http2
